name: 🚀 CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  IMAGE_NAME: yt-ninjas
  AWS_REGION: us-east-1
  EC2_HOST: ec2-54-159-95-146.compute-1.amazonaws.com
  EC2_USER: ec2-user
  DIRECTORY: /home/ec2-user/yt-ninjas

jobs:
  # ===== BUILD, TEST, LINT =====
  build-and-test:
    name: 🔨 Build & Test
    uses: ./.github/workflows/test-wf.yml
    with:
      node-version: '24'
      run-security-scan: true

  # ===== DEPLOY =====
  deploy:
    name: 📦 Deploy
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: 🚀 Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ env.EC2_HOST }}
          USER: ${{ env.EC2_USER }}
        run: |
          # SSH connect to the server and deploy
          echo "SSH Connecting to $USER@$HOST"
          echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 -i github-ec2.pem ${USER}@${HOST} '
          echo "Current directory: $(pwd)"
          
          # Pull latest changes from git
          cd '"${DIRECTORY}"' || { echo "Directory not found"; exit 1; }
          git reset --hard HEAD || { echo "git reset failed"; exit 1; }
          git pull origin main || { echo "git pull failed"; exit 1; }
          echo "Pulled latest changes from git"
          
          # Install dependencies
          npm install || { echo "npm install failed"; exit 1; }
          
          # Cleanup any existing PM2 processes
          npm run cleanup || { echo "PM2 cleanup failed"; exit 1; }
          
          # Build the application
          npm run build || { echo "Build failed"; exit 1; }          
          
          # Start the application with PM2
          npm run pm2 || { echo "PM2 start failed"; exit 1; }
          echo "Application deployed with PM2"
          
          echo "Deployment completed ✅" 
          '