name: 🚀 CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  IMAGE_NAME: yt-ninjas
  AWS_REGION: us-east-1
  EC2_HOST: ec2-13-221-134-173.compute-1.amazonaws.com
  EC2_USER: ec2-user
  DIRECTORY: /home/ec2-user/yt-ninjas

jobs:
  # ===== BUILD, TEST, LINT =====
  build-and-test:
    name: 🔨 Build & Test
    uses: ./.github/workflows/test-wf.yml
    with:
      node-version: '24'
      run-tests: true
      run-lint: true

  # ===== DEPLOY =====
  deploy:
    name: 📦 Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v5

      - name: 🚀 Deploy
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ env.EC2_HOST }}
          USER: ${{ env.EC2_USER }}
        run: |
          # Use the SHA short format (7 chars) to match
          SHORT_SHA=${GITHUB_SHA:0:7}
          IMAGE_TAG="main-${SHORT_SHA}"
          
          # SSH connect to the server and deploy
          echo "SSH Connecting to $USER@$HOST"
          echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
          ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} '
          echo "Current directory: $(pwd)"
          
          # Pull latest changes from git
          cd '"${DIRECTORY}"' || { echo "Directory not found"; exit 1; }
          git pull origin main
          echo "Pulled latest changes from git"
          
          # Install dependencies
          npm install
          
          # Build the application
          npm run build
          
          # Run with pm2
          pm2 kill || echo "No PM2 process to kill"
          pm2 delete all || echo "No PM2 process to delete"
          npm run pm2
          echo "Application deployed with PM2"
          
          echo "Deployment completed ✅" 
          '