name: 🔧 Reusable Setup & Build

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version'
        required: false
        type: string
        default: '24'
      run-tests:
        description: 'Run tests'
        required: false
        type: boolean
        default: true
      run-lint:
        description: 'Run linting'
        required: false
        type: boolean
        default: true

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v5

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: 📋 Install dependencies
        run: npm ci

      - name: 🔒 Security audit
        if: ${{ inputs.run-security-scan }}
        run: npm audit --audit-level moderate || echo "No vulnerabilities found"

      - name: 📈 Upload artifacts
        if: ${{ inputs.run-tests && always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results.xml